"""
AI Alert ORM Model
==================
Stores adverse media intelligence alerts generated by the n8n Adverse Media
Early Warning Radar workflow. Each row represents one AI-analysed financial
news article that has been assessed by an LLM acting as a Senior Credit Risk
Analyst.

Business Value:
  - Replaces manual media monitoring (typically 3–4 hours/day for analysts)
  - Provides early warning of emerging counterparty credit & reputational risk
  - Creates an auditable trail of AI-generated risk assessments
  - Feeds directly into the Risk Intelligence Dashboard Live Feed panel

SQL Schema:
  TABLE ai_alerts (
    id               TEXT PRIMARY KEY,
    company_name     TEXT NOT NULL,        — Entity identified in adverse media
    risk_score       INTEGER NOT NULL,     — 1–10 severity (10 = critical)
    risk_summary     TEXT NOT NULL,        — AI 2-sentence assessment
    source_article   TEXT,                 — Original article text analysed
    source           TEXT DEFAULT 'N8N_WORKFLOW',
    is_acknowledged  INTEGER DEFAULT 0,   — Boolean (SQLite stores as 0/1)
    created_at       DATETIME NOT NULL,
    acknowledged_at  DATETIME,
    acknowledged_by  TEXT
  )

Indexes:
  idx_ai_alerts_score_created  ON ai_alerts(risk_score, created_at DESC)
  idx_ai_alerts_company        ON ai_alerts(company_name)
"""

import enum
from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import Column, DateTime, Index, Integer, String, Text

from app.database import Base


class AIAlertSource(str, enum.Enum):
    N8N_WORKFLOW     = "N8N_WORKFLOW"
    MANUAL           = "MANUAL"
    REGULATORY_FEED  = "REGULATORY_FEED"


class AIAlert(Base):
    __tablename__ = "ai_alerts"

    id              = Column(String,  primary_key=True, default=lambda: str(uuid4()))
    company_name    = Column(String(200), nullable=False, index=True)
    risk_score      = Column(Integer, nullable=False)           # 1–10
    risk_summary    = Column(Text,    nullable=False)
    source_article  = Column(Text,    nullable=True)            # Original article snippet
    source          = Column(String(50), default=AIAlertSource.N8N_WORKFLOW.value, nullable=False)
    is_acknowledged = Column(Integer, default=0, nullable=False)  # 0=open, 1=acknowledged
    created_at      = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    acknowledged_by = Column(String(100), nullable=True)


# Composite index: most common query (newest high-severity unacknowledged alerts)
Index("idx_ai_alerts_score_created", AIAlert.risk_score, AIAlert.created_at)
